In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import plotly.graph_objects as go
import plotly.express as px
from plotly.subplots import make_subplots
from IPython.display import HTML
import scipy.optimize as opt
from scipy.stats import linregress

In [2]:
def plot(mesh_basis, value, width=800, height=800):
    max_val = np.max(value[np.isfinite(value)])
    value[np.isinf(value)] = max_val

    contour = go.Contour(x=mesh_basis[0], y=mesh_basis[1], z=value, 
#                          colorscale="turbo", 
                         colorscale="balance",
                         contours_coloring='heatmap',
                         colorbar=dict(
                             title=r'',  # title here
                             # titleside='',
                             titlefont=dict(
                                 size=16)
                         ))

    fig = make_subplots()
    fig.add_trace(contour)
    fig.update_layout(width=width,
                      height=height,
                      xaxis=dict(tickangle=90),
                      font=dict(
                          size=18
                      )
                      )
    print('show')
    fig.show()

In [31]:
# raw = pd.read_table("./optimize/comsol.txt", sep="\s+")
raw = pd.read_excel("./optimize/Comsol 2.51GHz.xlsx", header=7)
# raw = pd.read_excel("./optimize/Comsol.xlsx", header=7)
raw_r = np.array(raw.iloc[0:, 0], dtype=np.float64)/(10**3)
raw_z = np.array(raw.iloc[0:, 1], dtype=np.float64)/(10**3)
raw_Bz = np.array(raw.iloc[0:, 2], dtype=np.float64)

In [32]:
r_basis = np.unique(np.round(raw_r, 6))
z_basis = np.unique(np.round(raw_z, 6))[:-1]

In [33]:
z_basis

array([-0.0125  , -0.012222, -0.011944, -0.011667, -0.011389, -0.011111,
       -0.010833, -0.010556, -0.010278, -0.01    , -0.009608, -0.009216,
       -0.008824, -0.008431, -0.008039, -0.007647, -0.007255, -0.006863,
       -0.006471, -0.006078, -0.005686, -0.005294, -0.004902, -0.00451 ,
       -0.004118, -0.003725, -0.003333, -0.002941, -0.002549, -0.002157,
       -0.001765, -0.001373, -0.00098 , -0.000588, -0.000196,  0.000196,
        0.000588,  0.00098 ,  0.001373,  0.001765,  0.002157,  0.002549,
        0.002941,  0.003333,  0.003725,  0.004118,  0.00451 ,  0.004902,
        0.005294,  0.005686,  0.006078,  0.006471,  0.006863,  0.007255,
        0.007647,  0.008039,  0.008431,  0.008824,  0.009216,  0.009608,
        0.01    ,  0.010278,  0.010556,  0.010833,  0.011111,  0.011389,
        0.011667,  0.011944,  0.012222,  0.0125  ])

In [34]:
r_basis

array([0.      , 0.000385, 0.000769, 0.001154, 0.001538, 0.001923,
       0.002308, 0.002692, 0.003077, 0.003462, 0.003846, 0.004231,
       0.004615, 0.005   , 0.005385, 0.005769, 0.006154, 0.006538,
       0.006923, 0.007308, 0.007692, 0.008077, 0.008462, 0.008846,
       0.009231, 0.009615, 0.01    , 0.010385, 0.010769, 0.011154,
       0.011538, 0.011923, 0.012308, 0.012692, 0.013077, 0.013462,
       0.013846, 0.014231, 0.014615, 0.015   , 0.015399, 0.015798,
       0.016197, 0.016596, 0.016995, 0.017394, 0.017793, 0.018192,
       0.018592, 0.018991, 0.01939 , 0.019789, 0.020188, 0.020587,
       0.020986, 0.021385, 0.021784, 0.022183, 0.022582, 0.022981,
       0.02338 , 0.023779, 0.024178, 0.024577, 0.024977, 0.025376,
       0.025775, 0.026174, 0.026573, 0.026972, 0.027371, 0.02777 ,
       0.028169, 0.028568, 0.028967, 0.029366, 0.029765, 0.030164,
       0.030563, 0.030962, 0.031362, 0.031761, 0.03216 , 0.032559,
       0.032958, 0.033357, 0.033756, 0.034155, 0.034554, 0.034

In [35]:
np.array([round(r_basis[i-1] - r_basis[i], 2) for i in range(1, len(r_basis))])

array([-0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0.,
       -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0.,
       -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0.,
       -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0.,
       -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0.,
       -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0.,
       -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0.,
       -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0.,
       -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0.,
       -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0.,
       -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0.,
       -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0.,
       -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0.,
       -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0., -0

In [36]:
r_z_plane = np.full((len(r_basis), len(z_basis)), np.nan).T

In [37]:
# for i in range(len(raw_Bz)):
#     # print(i, np.where(np.isclose(r_basis, np.round(raw_r, 6)[i]))[0][0])
#     r_z_plane[np.where(np.isclose(r_basis, np.round(raw_r, 6)[i]))[0][0]][np.where(np.isclose(z_basis, np.round(raw_z, 6)[i]))[0][0]] = raw_Bz[i]


for i in range(len(raw_Bz)):
    if np.round(raw_r[i], 6) in r_basis and np.round(raw_z[i], 6) in z_basis:
        r_z_plane[np.where(np.isclose(z_basis, np.round(raw_z[i], 6)))[0][0]][np.where(np.isclose(r_basis, np.round(raw_r[i], 6)))[0][0]] = raw_Bz[i]

In [38]:
r_z_plane[:,0]

array([10.96340893, 10.9710973 , 10.99522639, 11.03579621, 11.09199229,
       11.16691808, 11.26057359, 11.35731647, 11.48312856, 11.63800989,
       11.63549392, 11.46208244, 11.11777572, 10.60703997,  9.94552411,
        9.13322898,  8.18733333,  7.13244154,  5.96855796,  4.72180084,
        3.42280619,  2.07165845,  0.70044247,  0.66371412,  2.0118623 ,
        3.31720402,  4.54917845,  5.7076975 ,  6.76406344,  7.69529391,
        8.50138442,  9.16119097,  9.66170156, 10.00291538, 10.17414698,
       10.17414698, 10.00291538,  9.66170156,  9.16119097,  8.50138442,
        7.69529391,  6.76406344,  5.7076975 ,  4.54917845,  3.31720402,
        2.0118623 ,  0.66371412,  0.70044247,  2.07165845,  3.42280619,
        4.72180084,  5.96855796,  7.13244154,  8.18733333,  9.13322898,
        9.94552411, 10.60703997, 11.11777572, 11.46208244, 11.63549392,
       11.63800989, 11.48312856, 11.35731647, 11.26057359, 11.16691808,
       11.09199229, 11.03579621, 10.99522639, 10.9710973 ,      

In [39]:
plot([r_basis, z_basis], r_z_plane, width=1200, height=400)

show


In [40]:
fig = px.line(x=r_basis, y=r_z_plane[0], title='Trend')
fig.update_layout(
    height=600, width=1200, xaxis_title="Step", yaxis_title="Energy",
    font=dict(
        size=18
    )
)
fig.show()

In [41]:
selected_z_point = 7  # Z slice for field
mode = 1 # mode number

In [53]:
zone_size = [-0.02, 0.02]
points_count = 15
points_step = (zone_size[1]-zone_size[0])/points_count

basis_arange = np.arange(zone_size[0], zone_size[1]+points_step, points_step)

X, Y, Z = np.meshgrid(basis_arange, basis_arange, [z_basis[selected_z_point]])
# X, Y = np.meshgrid(np.concatenate((-r_basis[::-1], r_basis[1:])), np.concatenate((-r_basis[::-1], r_basis[1:])))
cartesian_plane = np.full((X.shape[0], Y.shape[1], Z.shape[2]), np.nan)

In [54]:
np.max(r_basis)

0.119986

In [55]:
print("Slice at ", z_basis[selected_z_point])
for i in range(X.shape[0]):
    for j in range(Y.shape[1]):
        if np.sqrt(X[0][i] ** 2 + Y[j][0] ** 2) <= np.max(r_basis):
            cartesian_plane[i][j][0] = np.interp(np.sqrt(X[0][i] ** 2 + Y[j][0] ** 2), r_basis, r_z_plane[selected_z_point]*np.cos(mode*np.arctan2(X[0][i], Y[j][0])))


Slice at  -0.010556


In [56]:
cartesian_plane[:,:,0]

array([[-0.1386224 , -0.15376372, -0.1719131 , -0.18862274, -0.19481963,
        -0.17727342, -0.12710043, -0.04643999,  0.04643999,  0.12710043,
         0.17727342,  0.19481963,  0.18862274,  0.1719131 ,  0.15376372,
         0.1386224 ,  0.12724434],
       [-0.17741967, -0.21426589, -0.26453858, -0.31909216, -0.35737377,
        -0.34580439, -0.25811984, -0.09626837,  0.09626837,  0.25811984,
         0.34580439,  0.35737377,  0.31909216,  0.26453858,  0.21426589,
         0.17741967,  0.15247941],
       [-0.23442696, -0.3126365 , -0.42574334, -0.56167149, -0.67387861,
        -0.68548084, -0.51164846, -0.19617893,  0.19617893,  0.51164846,
         0.68548084,  0.67387861,  0.56167149,  0.42574334,  0.3126365 ,
         0.23442696,  0.1858766 ],
       [-0.31437123, -0.46091089, -0.68648738, -0.97189315, -1.1938464 ,
        -1.37802874, -1.16679342, -0.45959768,  0.45959768,  1.16679342,
         1.37802874,  1.1938464 ,  0.97189315,  0.68648738,  0.46091089,
         0.31437123

In [57]:
plot([X[0, :, 0], Y[:, 0, 0]], cartesian_plane[:,:,0], height=800, width=800)

show


In [58]:
def save_dataframe(mesh, value):
    xv, yv, zv = mesh

    Fx = value[0]
    Fy = value[1]
    Fz = value[2]

    np.savetxt("output.txt", np.transpose((xv.ravel(), yv.ravel(), zv.ravel(), Fx.ravel(), Fy.ravel(), Fz.ravel())), delimiter='\t', newline='\n')

In [59]:
save_dataframe([X, Y, Z], [np.full((X.shape[0], Y.shape[1], Z.shape[2]), 0), np.full((X.shape[0], Y.shape[1], Z.shape[2]), 0), cartesian_plane])